### ISSUE TITLE
[TASK] Make sentence block list view

### ISSUE THREAD

**Issue by jso4967** [jso4967/Subtube#36]
![image.png](https://images.zenhubusercontent.com/5d70acb91325bafe06b01379/edb8a1f7-864e-498b-b91e-ddf40af1e1ad)
- 위 이미지에서 영상  나오는 부분과 오른쪽은 빈칸으로 레이아웃만 잡아두고, 나머지 html, css, js로 구현
- 각 블록 클릭 이벤트 리스너 달기 // 클릭하면 블록 색깔 변하는 걸로? 알아서잘딱깔끔하고센스있게
- url 라우팅 // 어떤 url 형식을 할건지 정해서 url만 잡아주면 될듯
- db에서 자막 데이터 불러와서 동적으로 블록 생성해서 뿌려주기

**Comment by forbid403** [comment]
2번까지 완료
